### ISSUE TITLE
NoiseRemove Stereo ?

### ISSUE THREAD

**Issue by fredvs** [andrewd207/PascalAudio#1]
Hello Andrew.

Congratulation for that wonderful project. 

Your NoiseRemove demo is very impressive.

But It seems to me that it is working only for mono-audio files.

Here, in attachment, the mono noise.ogg and noisyaudio.ogg converted into stereo.
[noiseremovalstereo.zip](https://github.com/andrewd207/PascalAudio/files/140719/noiseremovalstereo.zip)

On my Linux 64 bit system, it does not work.

Thanks.

Fre;D

**Comment by andrewd207** [comment]
Fixed in 96fa220ddc32b0b6d2f21316a30211339b2fd889.

Thanks
